### ISSUE TITLE
Vis altid beløb med 2 decimaler i html-former

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/MarketSim#105]
Det drejer sig om to former: formen i create.html og formen i play.html. 

Lige nu vises hele beløb uden decimaler, og beløb, som er delelige med 0.10, vises blot med en enkelt decimal.

F.eks. skal initial balance i create market formen vises som 5000,00 i stedet for 5000. Jeg ved pt. ikke, hvordan man realiserer dette. Men i market_edit.html vises decimaltallene af en eller anden grund med alle decimaler - præcis som vi ønsker det. Så hvis vi kan forstå, hvorfor dette sker, kan det måske vise vej til løsningen.

**Comment by dybber** [comment]
Enig. Må være relativt simpelt at løse. Evt. sammen med NaN-problemet i #118
