### ISSUE TITLE
"Mine markeder" - ændr "Monitor" linket til noget mere meningsfyldt

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#116]
"Monitor" i tabellen er lidt indforstået - det er vores terminologi for siderne. Jeg tror måske bare der skal stå "Show market" eller "Vis marked" fremfor "Monitor" i linket til højre. Evt. skal den kolonne slet ikke være der og titlen på markedet i stedet være clickable.

**Comment by KristianMSchmidt** [comment]
Jeg er helt enig og havde tænkt over noget af det samme selv. Jeg sletter kolonnen og gør markedets ID clickable i stedet.

**Comment by dybber** [comment]
Super
