### ISSUE TITLE
OperationalError at /my_markets/  no such column: market_market.game_over

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#117]
> In template /code/market/templates/market/base.html, error at line 7
> no such column: market_market.game_over

![Screenshot 2021-08-30 at 14 47 35](https://user-images.githubusercontent.com/55204/131341321-ed7e0a9e-cfcc-41fc-acfe-4a3de40158bd.png)

Fejlen efter følgende:
 - opret bruger
 - opret marked
 - join marked med en bruger
 - kør 15 runder af markedet til det er afsluttet
 - i løbet af de 15 runder kunne jeg sagtens vise "Mine markeder"-siden
 - efter spillet var færdigt kunne jeg ikke længere få vist "Mine markeder"

**Comment by KristianMSchmidt** [comment]
Jeg har ikke umiddelbart denne fejl lokalt. Jeg spiller et spil til ende, tilgår "mine markeder" og så kan jeg se markedet med en besked om, at markedet er "game over". Dette er implementeret i my_market.html  sådan her: {% if market.game_over %} <td>Game over</td>.

Jeg gætter umiddelbart på, at problemet handler om, at din lokale database ikke er opdateret med nyeste ændringer (market.game_over eksisterer ikke længere som et field i databasen, men er en metode). Det minder lidt om de problemer, jeg beskrev i morges, og hvor det eneste, som virkede for mig var at slette min lokale volume med databasen. Bør vi måske gøre dette ved hver build af containeren, så vi har 100% det samme udgangspunkt hver gang?

**Comment by dybber** [comment]
Det har du nok ret i. Måske mangler jeg bare at køre `make build`. Idéen var at man nok ikke ville gide vente på at et nyt image bliver konstrueret hver eneste gang man kører serveren, men det kræver så at man husker at køre `make build` når der er sket ændringer i database-layoutet. Måske kan man gøre det på en smartere måde...

**Comment by dybber** [comment]
Men i teorien burde vi jo ikke behøve genskabe databasen, for ellers skal vi jo også slette databasen i produktion hver gang vi lægger en ny version op.

**Comment by dybber** [comment]
Jeg er ret sikker på det bare var en fejl-40 fra min side, hvor jeg ikke stod i master da jeg testede, men i stedet stod jeg ovre i den branch hvor jeg arbejder på at skifte over til pytest. 

Jeg er faktisk lidt usikker på hvad praksis er i forhold til at bruge migrations når man arbejder på forskellige branches. I det tilfælde sker der jo det at min branch er relativt langt bagud ift. database-layoutet, mens den database jeg arbejder på måske har fået anvendt nogle nye migrations (eller omvendt). Det kan godt være du har ret i at man skal genskabe hele databasen fra bunden ved hver eneste gang man kører udviklerserveren.
