### ISSUE TITLE
NaN when selecting data for next round

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#118]
Når man starter på en ny runde ser spiller-siden sådan her ud. 

![](https://user-images.githubusercontent.com/55204/131339191-f6818cce-1bec-49f7-8385-672b528d8055.png)

Bemærk NaN værdierne. Hvis man trykker "Lav din handel!" bliver man redirected tilbage uden fejlmeddelelse og uden at ens handel er foretaget. Efter man har ændret på prisen, er der ikke længere et NaN og når man har gjort det kan man godt gå videre til næste runde.

**Comment by KristianMSchmidt** [comment]
Jeg kan ikke umiddelbart reproducere denne fejl lokalt. Sker den hver gang?

**Comment by dybber** [comment]
Den sker igen nu efter migrations er anvendt. For at finde ud af om det var et klient-side problem, testede jeg også i Safari, hvor problemet IKKE opstår. Problemet opstår i Firefox, men altså ikke i Safari. Jeg har ikke lige Chrome installeret, så ved ikke hvordan den klarer det.

**Comment by dybber** [comment]
Mit bud er altså at problemet opstår her et sted:

https://github.com/DatalogiForAlle/MarketSim/blob/4d373fe51e1d70d9b78fd98bb8c5ccf63c0e2f0f/market/templates/market/play.html#L431-L457

Hvor variablen `best_case_income` bliver NaN, fordi `price` starter ud med ikke at være sat ind til brugeren har justeret på prisen hvorefter den får en værdi.

Måske mangler der bare et `parseFloat` som på linjen lidt længere oppe? Den linje ser jo ud til at virke.
https://github.com/DatalogiForAlle/MarketSim/blob/4d373fe51e1d70d9b78fd98bb8c5ccf63c0e2f0f/market/templates/market/play.html#L411

**Comment by KristianMSchmidt** [comment]
Hos mig opstår problemet hverken i Firefox eller Chrome. Men jeg skal nok kigge på det i andre browsere. Det er sikkert rigtigt, at problemer opstår i de linjer, du citerer. Uanset hvad skal der være en fejlmelding til brugeren, når formen ikke er udfyldt korrekt (jeg tænkte, at dette ikke ville kunne ske, da formen er en slider).

**Comment by dybber** [comment]
Måske kan jeg lige selv se på det og fx afprøve min teori om parseFloat vil have en effekt.

**Comment by dybber** [comment]
Fixet af #125
