### ISSUE TITLE
Should demand (from demand function) ever be allowed to be negative? Or should we limit it?

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#24]

**Comment by KristianMSchmidt** [comment]
In addition to this: Should all values of alpha, beta and theta be allowed in the CreateMarketForm? Or only non-negative values? Or only non-negative values bounded by some upper limit?

**Comment by dybber** [comment]
We should limit them to some sensible limits. The lower limits are described in the paper, for the upper limits we should perhaps ask the teacher involved (Niels) for advice on what is a meaningful range
