### ISSUE TITLE
Documentation of models

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#36]
I think it would be great with just a small amount of documentation for our models, in the places where it's not obvious from the code why we have made some decisions.

E.g. decribe what it means when certain fields are allowed to be null, what does the null indicate?

**Comment by KristianMSchmidt** [comment]
Where should we write the documentation? As comments in the code?

**Comment by dybber** [comment]
Yes, perhaps both a general comment for each model, and perhaps small comments on certain fields, where the choices of representation are non-obvious.
