### ISSUE TITLE
Distribute production costs uniformly

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/MarketSim#81]
When production costs range are 5-15, and at least 2 players, then the entire range of production costs should be used.

**Comment by JensKanstrupLarsen** [comment]
My suggestion for an algorithm:
- You have an initial selection of available numbers `a = [5,15]` (or an equivalent `[min, max]`) and a set of used numbers `b = []`.
- As players arrive, you pick a number at random from `a`, assign the player that number as production cost, then move the number to `b`.
- After 2 players have joined, you have `a = []` and `b = [5, 15]`.
- Now, you find the average number between all sequential pairs of used numbers (in this case, there is only one number: `(5+15)/2 = 10`), and add that number to `a`.
- Then you pick from `a` again until it runs out of numbers, and repeat.
- Using 5 and 15 as starting points, this gives `a` values of `[5, 15]` -> `[10]` -> `[7.5, 12.5]` -> `[6.25, 8.75, 11.25, 13.75]` -> ...

**Comment by KristianMSchmidt** [comment]
Sounds good to me!
