### ISSUE TITLE
Show product name in templates

### ISSUE THREAD

**Issue by KristianMSchmidt** [DatalogiForAlle/MarketSim#92]
If the product has a name (e.g. 'baguettes') it should be shown in the templates. The tricky part is to get the singular and plural forms right. Perhaps there is a library to do this in Danish? Otherwise, we might need to ask the users for both the singular and plural forms of the product name (computer/computere, cykel/cykler) when they create a market and store these values in the database...

**Comment by dybber** [comment]
I think the best solution is to let the user specify both the singular and plural forms when they create the market. For the most part users will probably select from our list of default settings, so it shouldn't be a problem.

**Comment by KristianMSchmidt** [comment]
Ok, I will implement this solution and add it to my current pull request (if it not yet merged by then)
